//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLChatThai.Models.QLCTModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("CTNhap")]
    
    public partial class CTNHap
    {
        [Key]
        public int idctnhap { get; set; }
        public int Sophieu { get; set; }
        public int idct { get; set; }
        public string Tenct { get; set; }
        public string dvt { get; set; }
        public string trangthai { get; set; }
        public int idxl { get; set; }
        public Nullable<float> slthuc { get; set; }
        public Nullable<float> slbaocao { get; set; }
        public Nullable<double> Dongianhap { get; set; }
        public bool loai { get; set; }
        public string status { get; set; }

        public virtual Xuly Xuly { get; set; }
        public virtual DM_CT DM_CT { get; set; }
        public virtual Nhap Nhap { get; set; }
    }
}
