//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLChatThai.Models.QLCTModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel;

    [Table("DM_CT")]
    public partial class DM_CT
    {
        public DM_CT()
        {
            this.CTNHaps = new HashSet<CTNHap>();
        }
        [Key]
        public int idct { get; set; }
        public string Ma_CT { get; set; }
        public string Ten_CT { get; set; }
        public string Ma_EC { get; set; }
        public string Ma_BaselA { get; set; }
        public string Ma_BaselY { get; set; }
        public string DVT { get; set; }
        public string TC_Nguyhai { get; set; }
        public string Trangthai_tontai { get; set; }
        public string Nguong_nguyhai { get; set; }
        public string status { get; set; }
        public string MaCap2 { get; set; }
        [DisplayName("Tự xử lý")]
        public bool tuxuly { get; set; }
        public virtual ICollection<CTNHap> CTNHaps { get; set; }
        //public virtual DMCap2 DMCap2 { get; set; }
    }
}
