//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLChatThai.Models.QLCTModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DMCap1")]
    
    public partial class DMCap1
    {
        public DMCap1()
        {
            this.DMCap2 = new HashSet<DMCap2>();
        }
        [Key]
        public string Macap1 { get; set; }
        public string Ten { get; set; }
    
        public virtual ICollection<DMCap2> DMCap2 { get; set; }
    }
}
