//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLChatThai.Models.QLCTModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DMCap2")]
    
    public partial class DMCap2
    {
        //public DMCap2()
        //{
        //    this.DM_CT = new HashSet<DM_CT>();
        //}
        [Key]
        public string Macap2 { get; set; }
        public string Ten { get; set; }
        public string Ma_EC { get; set; }
        public string Macap1 { get; set; }
    
        //public virtual ICollection<DM_CT> DM_CT { get; set; }
        public virtual DMCap1 DMCap1 { get; set; }
    }
}
