//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLChatThai.Models.QLCTModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("DMKho")]
    
    public partial class DMKHO
    {
        public DMKHO()
        {
            this.Nhaps = new HashSet<Nhap>();
        }
        [Key]
        public int makho { get; set; }
        public string Tenkho { get; set; }
    
        public virtual ICollection<Nhap> Nhaps { get; set; }
    }
}
