//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLChatThai.Models.QLCTModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Khachhang")]
    
    public partial class Khachhang
    {
        public Khachhang()
        {
            this.Nhaps = new HashSet<Nhap>();
        }
        
        [Key]
        public string Code_KH { get; set; }
        public string Ten_KH { get; set; }
        public string Diachi_VP { get; set; }
        public string Diachi_CS { get; set; }
        public string Dienthoaivp { get; set; }
        public string Dienthoaics { get; set; }
        public string MS_QLCTNH { get; set; }
        public int Ma_tinh { get; set; }
            
        public virtual Tinhthanh Tinhthanh { get; set; }
        public virtual ICollection<Nhap> Nhaps { get; set; }
    }
}
