//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLChatThai.Models.QLCTModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Nhanvien")]
    
    public partial class Nhanvien
    {
        public Nhanvien()
        {
            this.Nhaps = new HashSet<Nhap>();
        }
        [Key]
        public string manv { get; set; }
        public string fullname { get; set; }
        public string Bophan { get; set; }
        public string Congviec { get; set; }
        public string password { get; set; }
        public string status { get; set; }
        public bool activated { get; set; }
    
        public virtual ICollection<Nhap> Nhaps { get; set; }
    }
}
